### ISSUE TITLE
[Bug] [Arch] [Glasscord] Can't connect to proxy

### ISSUE THREAD

**Issue by BitterSweetcandyshop** [Mastermindzh/tidal-hifi#109]
I use glasscord, but I seem to be facing an issue that I don't know is from using glasscord.
![image](https://user-images.githubusercontent.com/97067423/158000171-2cfc1e44-9e3a-4fa2-aeac-8b76653452c4.png)

I gave glasscord a delay of 1000ms and applied the following css:
```css
.css-1ezs1pk, .css-1emr5z5, .contentArea--1raSP, .css-9dfit8 {
    background-color: transparent !important
}

.enable-scrollbar-styles {
    background-color: rgba(0, 0, 0, 0.5)
}
```
Before adding the css loading, it worked fine but now I"m getting the proxy error.

It does eventually load and starts working just fine, but it takes ages for that to happen.
