### ISSUE TITLE
Custom css

### ISSUE THREAD

**Issue by iammilandwl** [Mastermindzh/tidal-hifi#213]
Maybe a way to add custom css to the app? idk just an idea

**Comment by Mastermindzh** [comment]
Hey @iammilandwl,

I'll start working on this feature and expect to have it finished later today.
It will be included in release 5.1.0 😄

**Comment by Mastermindzh** [comment]
![image](https://user-images.githubusercontent.com/4190290/234857498-749f5f55-a7f8-46c0-bed2-3efab59c1f53.png)

About to merge 😄

**Comment by wojciech-zurek** [comment]
Thank you. It  works as expected. Tokyo night inspiration :)
![tidal](https://user-images.githubusercontent.com/622981/236612987-41dbf04f-1621-4ec5-bb86-c84551774946.png)

**Comment by Mastermindzh** [comment]
Hey,

Very cool!
Maybe I should make it possible to have themes 🤔.

Want to dump/mail me your custom CSS to see what I can whip up 😄 ?

**Comment by wojciech-zurek** [comment]
@Mastermindzh 
My custom css.  Not all items have been changed.

```css
"customCSS": ":root { --footer-player-background: #1a1b26; --sidebar-background: #1a1b26; --sidebar-hover-background: #414868; --sidebar-menu-top-text: #565f89; --sidebar-menu-playlist-text: #565f89; --search-background: #1a1b26l; --main-background: #16161e; --main-navigation-control-background: #1a1b26; --main-feed-button-background: #1a1b26; --player-control-background: #24283b; --player-control-active-button: #ff9e64; --player-progress-bar: #ff9e64; --indicator-hifi-background: #9ece6a; --indicator-hifi-span: #1a1b26; --player-control-favorite: #f7768e; --search-dialog-background: #24283b; --right-queue-background: #24283b; } .player--fNPGt.notFullscreen--ugyc2 {background-color: var(--footer-player-background);} .sidebar--WvRg_ { background-color: var(--sidebar-background); contain: strict; flex-grow: 1; overflow-y: auto;} .item--VTpWS:hover {background-color: var(--sidebar-hover-background);} .main--LUnJp { background-color: var(--main-background); } button.button--ncJwL { background-color: var(--main-navigation-control-background);} .player--fNPGt.lossLess--g5Jss button.withBackground[aria-checked='true'] path { fill: var(--player-control-active-button);} .player--fNPGt.lossLess--g5Jss button.withBackground[aria-checked='true'] {background-color: var(--player-control-background); } .activeItem--qV6eL .activeItem--qV6eL .playlistItem--YARJh .section--FI41E.playingItem--eWkYS {color: #565f89;} .progressBarWrapper--WZfox {color: var(--player-progress-bar);} .playbackControls--FLeZA button .tidal-ui__icon {transform: scale(1);} .css-11m9iw3 {background-color: var(--indicator-hifi-background); } .css-11m9iw3 span {color: var(--indicator-hifi-span);} .activeItem--qV6eL { color: var(--sidebar-menu-top-text) } .activeItem--qV6eL .playlistItem--YARJh {color: var(--sidebar-menu-playlist-text);} button.feedBell--B8anb {background-color: var(--main-feed-button-background);} .baseContainer--cbf17 { background-color: var(--search-dialog-background);} .favoriteButton--TtBlM.is-favorite path { fill: var(--player-control-favorite);} .container--mkEWd { background-color: var(--right-queue-background)} .container--vJVjO { background-color: var(--search-background);} .searchFieldHighlighted--Fitvs {color: var(--snow-white)}"
```

I think the best way is to separate the definition of colours from the css selectors.

Btw: I'm not a frontent developer ;)
