### ISSUE TITLE
Arch install failing

### ISSUE THREAD

**Issue by rarescosma** [Mastermindzh/tidal-hifi#26]
Hey, Arch AUR install started failing today to due `electron-builder` trying to pull electron from the official repository, but they don't have widevine releases:

```
  • packaging       platform=linux arch=x64 electron=8.5.2-wvvmp appOutDir=dist/linux-unpacked
  ⨯ cannot resolve https://github.com/electron/electron/releases/download/v8.5.2-wvvmp/electron-v8.5.2-wvvmp-linux-x64.zip: status code 404
```

Temporary fix was to create a separate `/tmp/build-config.yml` for `electron-builder` and abuse the mirror support to point it to the castlabs repo:

```
directories:
  output: dist
  buildResources: build
electronVersion: 8.5.2-wvvmp
electronDownload:
  mirror: https://github.com/castlabs/electron-releases/releases/download/v
```

Then in `PKGBUILD`:

```
npx electron-builder --linux --config /tmp/build-config.yml dir
```
